version: '2'
services:
  db:
    image: yobasystems/alpine-mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /mnt/pi/meta/mysql_ncloud:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD='shivam99'
      - MYSQL_PASSWORD='shivam99'
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  app:
    image: nextcloud
    ports:
      - 8181:80
    links:
      - db
    volumes:
      - /mnt/pi/meta/nextcloud:/var/www/html
      - /mnt/pi/smb_share:/pi_smb
      - /mnt/backup/smb_share:/backup_smb
    restart: always
